apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: paascoe-deployment
spec:
  selector:
    matchLabels:
      app: paascoe
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: paascoe
    spec:
      containers:
      - name: paascoe
        image: sauravsrivastav/paascoe:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        env:
          - name: ConnectionStrings__EmployeesContext
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: db-connection-string-secret

---
kind: Service
apiVersion: v1
metadata:
  name: paascoe-service
spec:
  selector:
    app: paascoe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer