apiVersion: v1
kind: Secret
metadata:
  name:  mssql-secret
data:
   db-connection-string-secret: U2VydmVyPW1zc3FsLXNlcnZpY2U7RGF0YWJhc2U9RW1wbG95ZWVzREI7VXNlcj1TQTtQYXNzd29yZD1TYXVyYXZAMTIzOw==
type: Opaque